### ISSUE TITLE
Firefox hangs when Ctrl+F is pressed with pwgen enabled

### ISSUE THREAD

**Issue by Shadorino** [alouche/pwgen#10]
Firefox freezes randomly or immediately after pressing Ctrl+F when pwgen is enabled. The mention "not responding" is not present in the task manager next to Firefox though.
This happens with the 32 and 64-bit version of Firefox, I've done a clean install of Windows since it first appeared. I think the first time I encountered this was not before Firefox 41.0.

This script could be the problem : chrome://browser/content/browser.js:16152
although I don't have any idea what a script is  XD

This is a great add on by the way

**Comment by Shadorino** [comment]
Well, never mind that, pwgen is the not the one that's causing the freeze. This thing is driving me crazy.
Sorry for this post  :)

**Comment by alouche** [comment]
No worries :) - Good luck on fixing your issues.

**Comment by Shadorino** [comment]
Thanks :)
